apiVersion: v1
kind: Service
metadata:
  name: {{ include "solr.fullname" . }}-service
  labels:
    app.kubernetes.io/name: {{ include "solr.name" . }}
    helm.sh/chart: {{ include "solr.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: "solr-client"
  selector:
    app.kubernetes.io/name: {{ include "solr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "solr-server"
